-- KnowFlow AI 数据库建表脚本
-- 使用场景：
-- 1. 前端同学直接在 Neon 控制台的 SQL Editor 中复制执行
-- 2. 本地 Python 脚本读取本文件并一键执行
--
-- 设计来源：文档《KnowFlow_AI_RAG_智能问答系统_从0到1实现文档》第 9 点数据库表设计
-- 默认行为：在当前 schema 下创建表。Neon 通常默认是 public schema。

BEGIN;

-- =========================================================
-- 1. 枚举类型
-- =========================================================
-- 文档处理状态
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'document_status_enum'
          AND n.nspname = current_schema()
    ) THEN
        CREATE TYPE document_status_enum AS ENUM (
            'uploaded',
            'parsing',
            'chunking',
            'chunked',
            'embedding',
            'indexed',
            'failed'
        );
    END IF;
END $$;

-- 聊天消息角色
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'chat_role_enum'
          AND n.nspname = current_schema()
    ) THEN
        CREATE TYPE chat_role_enum AS ENUM (
            'user',
            'assistant',
            'system'
        );
    END IF;
END $$;

-- 模型类型
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'model_type_enum'
          AND n.nspname = current_schema()
    ) THEN
        CREATE TYPE model_type_enum AS ENUM (
            'chat',
            'embedding',
            'rerank'
        );
    END IF;
END $$;

-- 问答反馈类型
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'feedback_rating_enum'
          AND n.nspname = current_schema()
    ) THEN
        CREATE TYPE feedback_rating_enum AS ENUM (
            'like',
            'dislike'
        );
    END IF;
END $$;

-- =========================================================
-- 2. 自动更新时间函数
-- =========================================================
-- 用于自动刷新 updated_at 字段，避免每次 update 都手写 NOW()
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 3. 用户表
-- =========================================================
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE users IS '用户表：当前是单用户 MVP，但保留标准用户结构。';

-- =========================================================
-- 4. 知识库表
-- =========================================================
CREATE TABLE IF NOT EXISTS knowledge_bases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE knowledge_bases IS '知识库表：一个知识库对应一组文档。';

-- =========================================================
-- 5. 文档表
-- =========================================================
CREATE TABLE IF NOT EXISTS documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id INTEGER NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    -- MIME 类型可能很长（如 Office Open XML），需预留足够长度。
    file_type VARCHAR(255) NOT NULL,
    file_path VARCHAR(1024) NOT NULL,
    file_size INTEGER NOT NULL,
    status document_status_enum NOT NULL,
    error_message TEXT,
    chunk_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE documents IS '文档表：保存上传文件及其解析/切片/向量化状态。';

-- =========================================================
-- 6. 文档切片表
-- =========================================================
CREATE TABLE IF NOT EXISTS document_chunks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    knowledge_base_id INTEGER NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    page_number INTEGER,
    token_count INTEGER NOT NULL,
    vector_id VARCHAR(128),
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_document_chunks_document_chunk_index UNIQUE (document_id, chunk_index)
);

COMMENT ON TABLE document_chunks IS '文档切片表：保存每个 chunk 的文本、页码、token 数和向量 ID。';

-- =========================================================
-- 7. 聊天会话表
-- =========================================================
CREATE TABLE IF NOT EXISTS chat_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id INTEGER NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE chat_sessions IS '聊天会话表：一轮或多轮问答的容器。';

-- =========================================================
-- 8. 聊天消息表
-- =========================================================
CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role chat_role_enum NOT NULL,
    content TEXT NOT NULL,
    token_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE chat_messages IS '聊天消息表：保存用户消息、助手消息和系统消息。';

-- =========================================================
-- 9. 聊天引用表
-- =========================================================
CREATE TABLE IF NOT EXISTS chat_references (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chunk_id INTEGER NOT NULL REFERENCES document_chunks(id) ON DELETE CASCADE,
    score DOUBLE PRECISION NOT NULL,
    content_preview TEXT NOT NULL,
    page_number INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE chat_references IS '聊天引用表：标记答案引用了哪些文档切片。';

-- =========================================================
-- 10. Prompt 模板表
-- =========================================================
CREATE TABLE IF NOT EXISTS prompt_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    description TEXT,
    template TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE prompt_templates IS 'Prompt 模板表：保存系统提示词和业务提示词模板。';

-- =========================================================
-- 11. 模型配置表
-- =========================================================
CREATE TABLE IF NOT EXISTS model_configs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(100) NOT NULL,
    base_url VARCHAR(512) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    model_type model_type_enum NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE model_configs IS '模型配置表：保存聊天模型、Embedding 模型、Rerank 模型配置。';

-- =========================================================
-- 12. 问答反馈表
-- =========================================================
CREATE TABLE IF NOT EXISTS question_feedbacks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    rating feedback_rating_enum NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE question_feedbacks IS '问答反馈表：保存点赞/点踩和补充说明。';

-- =========================================================
-- 13. 评测用例表
-- =========================================================
CREATE TABLE IF NOT EXISTS evaluation_cases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id INTEGER NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    expected_answer TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE evaluation_cases IS '评测用例表：保存标准问题和期望答案。';

-- =========================================================
-- 14. 评测结果表
-- =========================================================
CREATE TABLE IF NOT EXISTS evaluation_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id INTEGER NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    case_count INTEGER NOT NULL,
    avg_score DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE evaluation_runs IS '评测结果表：保存某次批量评测的汇总结果。';

-- =========================================================
-- 15. 索引
-- =========================================================
-- 常见查询路径提前加索引，减少后续接口查询的全表扫描
CREATE INDEX IF NOT EXISTS ix_knowledge_bases_owner_id
ON knowledge_bases (owner_id);

CREATE INDEX IF NOT EXISTS ix_documents_knowledge_base_id
ON documents (knowledge_base_id);

CREATE INDEX IF NOT EXISTS ix_document_chunks_document_id
ON document_chunks (document_id);

CREATE INDEX IF NOT EXISTS ix_document_chunks_knowledge_base_id
ON document_chunks (knowledge_base_id);

CREATE INDEX IF NOT EXISTS ix_document_chunks_content_hash
ON document_chunks (content_hash);

CREATE INDEX IF NOT EXISTS ix_document_chunks_vector_id
ON document_chunks (vector_id);

CREATE INDEX IF NOT EXISTS ix_chat_sessions_knowledge_base_id
ON chat_sessions (knowledge_base_id);

CREATE INDEX IF NOT EXISTS ix_chat_sessions_user_id
ON chat_sessions (user_id);

CREATE INDEX IF NOT EXISTS ix_chat_messages_session_id
ON chat_messages (session_id);

CREATE INDEX IF NOT EXISTS ix_chat_references_message_id
ON chat_references (message_id);

CREATE INDEX IF NOT EXISTS ix_chat_references_document_id
ON chat_references (document_id);

CREATE INDEX IF NOT EXISTS ix_chat_references_chunk_id
ON chat_references (chunk_id);

CREATE INDEX IF NOT EXISTS ix_model_configs_provider_model_type
ON model_configs (provider, model_type);

CREATE INDEX IF NOT EXISTS ix_question_feedbacks_message_id
ON question_feedbacks (message_id);

CREATE INDEX IF NOT EXISTS ix_evaluation_cases_knowledge_base_id
ON evaluation_cases (knowledge_base_id);

CREATE INDEX IF NOT EXISTS ix_evaluation_runs_knowledge_base_id
ON evaluation_runs (knowledge_base_id);

-- =========================================================
-- 16. 自动更新时间触发器
-- =========================================================
-- 所有带 updated_at 的表，都在 update 时自动刷新该字段
DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users;
CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_knowledge_bases_set_updated_at ON knowledge_bases;
CREATE TRIGGER trg_knowledge_bases_set_updated_at
BEFORE UPDATE ON knowledge_bases
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_documents_set_updated_at ON documents;
CREATE TRIGGER trg_documents_set_updated_at
BEFORE UPDATE ON documents
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_chat_sessions_set_updated_at ON chat_sessions;
CREATE TRIGGER trg_chat_sessions_set_updated_at
BEFORE UPDATE ON chat_sessions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_prompt_templates_set_updated_at ON prompt_templates;
CREATE TRIGGER trg_prompt_templates_set_updated_at
BEFORE UPDATE ON prompt_templates
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_model_configs_set_updated_at ON model_configs;
CREATE TRIGGER trg_model_configs_set_updated_at
BEFORE UPDATE ON model_configs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
